#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x42C9C8D3AF5EA5E3 (agaida@siduction.org)
#
Name     : lxqt-policykit
Version  : 0.14.0
Release  : 1
URL      : https://downloads.lxqt.org/downloads/lxqt-policykit/0.14.0/lxqt-policykit-0.14.0.tar.xz
Source0  : https://downloads.lxqt.org/downloads/lxqt-policykit/0.14.0/lxqt-policykit-0.14.0.tar.xz
Source99 : https://downloads.lxqt.org/downloads/lxqt-policykit/0.14.0/lxqt-policykit-0.14.0.tar.xz.asc
Summary  : The LXQt policykit authentication agent
Group    : Development/Tools
License  : LGPL-2.1
Requires: lxqt-policykit-bin = %{version}-%{release}
Requires: lxqt-policykit-data = %{version}-%{release}
Requires: lxqt-policykit-license = %{version}-%{release}
Requires: lxqt-policykit-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : liblxqt-dev
BuildRequires : lxqt-build-tools
BuildRequires : pkg-config
BuildRequires : pkgconfig(polkit-agent-1)
BuildRequires : polkit-qt-dev
BuildRequires : qttools-dev

%description
# lxqt-policykit
## Overview
lxqt-policykit is the polkit authentification agent of LXQt.

%package bin
Summary: bin components for the lxqt-policykit package.
Group: Binaries
Requires: lxqt-policykit-data = %{version}-%{release}
Requires: lxqt-policykit-license = %{version}-%{release}
Requires: lxqt-policykit-man = %{version}-%{release}

%description bin
bin components for the lxqt-policykit package.


%package data
Summary: data components for the lxqt-policykit package.
Group: Data

%description data
data components for the lxqt-policykit package.


%package license
Summary: license components for the lxqt-policykit package.
Group: Default

%description license
license components for the lxqt-policykit package.


%package man
Summary: man components for the lxqt-policykit package.
Group: Default

%description man
man components for the lxqt-policykit package.


%prep
%setup -q -n lxqt-policykit-0.14.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549560651
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1549560651
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lxqt-policykit
cp LICENSE %{buildroot}/usr/share/package-licenses/lxqt-policykit/LICENSE
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lxqt-policykit-agent

%files data
%defattr(-,root,root,-)
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_ar.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_ca.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_cs.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_cy.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_da.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_de.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_el.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_es.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_fr.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_gl.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_he.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_hu.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_id.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_it.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_ja.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_lt.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_nb_NO.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_nl.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_pl.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_pt.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_ru.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_tr.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_uk.qm
/usr/share/lxqt/translations/lxqt-policykit-agent/lxqt-policykit-agent_zh_CN.qm

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lxqt-policykit/LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/lxqt-policykit-agent.1
